### PR TITLE
JENKINS-60868 Jobs using the Parameterized Scheduler Plugin are now supported

### PR DESCRIPTION
**Pull request by malice00**
Fix for JENKINS-60868: Support for Parameterized Scheduler Plugin added

### CODE REVIEW

**Comment by pespinel** [comment]
@malice00 Any update?

**Comment by malice00** [comment]
@pespinel Not from my side... I made this PR and now it should be merged and released.... But I have a feeling this plugin is dying or already dead...

**Comment by alexander-gorelik** [comment]
Any update on that issue?

**Comment by oleg-nenashev** [comment]
@svenschoenung Hi, there is the plugin adoption request in https://groups.google.com/g/jenkinsci-dev/c/I03rPPkYSTY. If you have no time to maintain the plugin, it would be great to get your approval there.

**Review by dimaka-wix — APPROVED** [review]

**Comment by ivoferro** [comment]
Hi, any updates on this? This feature brings a lot of value.

**Comment by malice00** [comment]
Good news: I have gotten the necessary permissions to work on this plugin. I need a couple of days to figure everything out and familiarize myself with workflows and stuff, but I hope to release this soon after that!

**Comment by dimaka-wix** [comment]
> Good news: I have gotten the necessary permissions to work on this plugin. I need a couple of days to figure everything out and familiarize myself with workflows and stuff, but I hope to release this soon after that!

Greate news!
I also found out that it doesn't support TZ in cron jobs. 
For example, if the cron looks like that:
```
 parameterizedCron(
'''TZ=Europe/Kiev
0 11 * * * %KEY=value'''
)
```
The job will run at 11:00, but if the server time is different the calendar will display it according to the server timezone and not according to Kiev timezone.
It looks like, the calendar plugin doesn't have any logic about the TZ shifting(but I didn't check the source code yet)

**Comment by malice00** [comment]
@dimaka-wix Please file a new Bug-Report for that, otherwise it might get lost when I merge this PR!

@everybody I found something in this PR which I want to check before merging, but I'm on it now!

**Pull request merged**
